= Questory API Documentation
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 3
:sectlinks:
:sectnums:

== Auth API

=== 1. Ticket Exchange

OAuth2 로그인 성공 후 발급된 일회용 ticket을 Access Token으로 교환합니다.

PKCE가 적용된 OAuth2 로그인인 경우 `code_verifier`를 함께 전달해야 합니다.

==== 1-1. exchange 성공 (200)

operation::auth-exchange[snippets='http-request,http-response,request-fields,response-headers,response-fields']

==== 1-2. exchange 실패 (400 - Validation)

operation::auth-exchange-400[snippets='http-request,http-response,request-fields,response-fields']


=== 2. OAuth2 Social Login

==== 2-1. 소셜 로그인 요청 URL

아래 URL로 접근하면 각 Provider 인증 페이지로 리다이렉트됩니다.

- Kakao: `/oauth2/authorization/kakao`
- Naver: `/oauth2/authorization/naver`
- Google: `/oauth2/authorization/google`

==== 2-2. OAuth2 Callback URL (Provider → Backend)

각 Provider는 인증 완료 후 아래 엔드포인트로 콜백됩니다. (Spring Security 기본값)

- Kakao: `/login/oauth2/code/kakao`
- Naver: `/login/oauth2/code/naver`
- Google: `/login/oauth2/code/google`


== Member API

=== 1. 회원가입

==== 1-1. 회원가입 성공

operation::member-register[snippets='http-request,http-response,request-fields,response-fields']

==== 1-2. 회원가입 실패 (Validation)

operation::member-register-400[snippets='http-request,http-response,response-fields']


=== 2. 로그인

==== 2-1. 로그인 성공

operation::member-login[snippets='http-request,http-response,request-fields,response-headers']

==== 2-2. 로그인 실패 (Validation)

operation::member-login-400[snippets='http-request,http-response,response-fields']


=== 3. Access Token 재발급

==== 3-1. 재발급 성공

operation::member-refresh[snippets='http-request,http-response,response-headers']

==== 3-2. 재발급 실패 (refresh_token 없음)

operation::member-refresh-401-no-cookie[snippets='http-request,http-response,response-fields']


=== 4. 로그아웃

==== 4-1. 로그아웃 성공

operation::member-logout[snippets='http-request,http-response,response-headers']


== Account API

=== 1. 내 정보 조회

==== 1-1. 내 정보 조회 성공

operation::account-me-success[snippets='http-request,http-response,response-fields']


=== 2. 회원 탈퇴

==== 2-1. 회원 탈퇴 성공

operation::account-withdraw-success[snippets='http-request,http-response,response-fields']


=== 3. 회원 검색

==== 3-1. 회원 검색 성공

operation::account-search-success[snippets='http-request,http-response,response-fields']

==== 3-2. 회원 검색 실패 (email 파라미터 누락)

operation::account-search-500-missing-email[snippets='http-request,http-response,response-fields']


== 4. Title API

==== 4-1. 내 칭호 목록 조회 성공

operation::title-get-my-titles-success[snippets='http-request,http-response,response-fields']

==== 4-2. 칭호 획득 성공

operation::title-acquire-success[snippets='http-request,http-response,request-fields,response-fields']

==== 4-3. 대표 칭호 변경 성공

operation::title-update-representative-success[snippets='http-request,http-response,request-fields,response-fields']

==== 4-4. 칭호 획득 실패 (Validation)

operation::title-acquire-400-validation[snippets='http-request,http-response,response-fields']


== 5. Friend API

=== 1. 친구 목록

==== 1-1. 친구 목록 조회 성공 (200)

operation::friend-get-friends[snippets='http-request,http-response,response-fields']


=== 2. 친구 삭제

==== 2-1. 친구 삭제 성공 (200)

operation::friend-delete-friend[snippets='http-request,http-response,path-parameters,response-fields']


=== 3. 친구 요청

==== 3-1. 받은 친구 요청 목록 조회 성공 (200)

operation::friend-get-received-requests[snippets='http-request,http-response,response-fields']

==== 3-2. 친구 요청 보내기 성공 (201)

operation::friend-request-send[snippets='http-request,http-response,request-fields,response-fields']

==== 3-3. 친구 요청 보내기 실패 (400 - Validation: email blank)

operation::friend-request-send-400-blank-email[snippets='http-request,http-response,request-fields,response-fields']

==== 3-4. 친구 요청 보내기 실패 (400 - Validation: email invalid)

operation::friend-request-send-400-invalid-email[snippets='http-request,http-response,request-fields,response-fields']

==== 3-5. 친구 요청 보내기 실패 (400 - JSON 파싱 실패)

operation::friend-request-send-400-not-readable[snippets='http-request,http-response,response-fields']


=== 4. 보낸 친구 요청

==== 4-1. 보낸 친구 요청 목록 조회 성공 (200)

operation::friend-get-sent-requests[snippets='http-request,http-response,response-fields']


=== 5. 친구 요청 처리

==== 5-1. 친구 요청 수락 성공 (200)

operation::friend-request-accept[snippets='http-request,http-response,path-parameters,response-fields']

==== 5-2. 친구 요청 거절 성공 (200)

operation::friend-request-reject[snippets='http-request,http-response,path-parameters,response-fields']

==== 5-3. 친구 요청 취소 성공 (200)

operation::friend-request-cancel[snippets='http-request,http-response,path-parameters,response-fields']