= Questory API Documentation
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 3
:sectlinks:
:sectnums:

== Auth API

=== 1. Ticket Exchange

==== 1-1. exchange 성공 (200)

operation::auth-exchange[snippets='http-request,http-response,request-fields,response-headers,response-fields']

==== 1-2. exchange 실패 (400 - Validation)

operation::auth-exchange-400[snippets='http-request,http-response,request-fields']

=== 2. OAuth2 Social Login

==== 2-1. 소셜 로그인 요청 URL

아래 URL로 접근하면 각 Provider 인증 페이지로 리다이렉트됩니다.

- Kakao: `/oauth2/authorization/kakao`
- Naver: `/oauth2/authorization/naver`
- Google: `/oauth2/authorization/google`

==== 2-2. OAuth2 Callback URL (Provider → Backend)

각 Provider는 인증 완료 후 아래 엔드포인트로 콜백됩니다. (Spring Security 기본값)

- Kakao: `/login/oauth2/code/kakao`
- Naver: `/login/oauth2/code/naver`
- Google: `/login/oauth2/code/google`


== Member API

=== 1. 회원가입

==== 1-1. 회원가입 성공

operation::member-register[snippets='http-request,http-response,request-fields,response-fields']

==== 1-2. 회원가입 실패 (Validation)

operation::member-register-400[snippets='http-request,http-response']


=== 2. 로그인

==== 2-1. 로그인 성공

operation::member-login[snippets='http-request,http-response,request-fields,response-headers']

==== 2-2. 로그인 실패 (Validation)

operation::member-login-400[snippets='http-request,http-response']


=== 3. Access Token 재발급

==== 3-1. 재발급 성공

operation::member-refresh[snippets='http-request,http-response,response-headers']

==== 3-2. 재발급 실패 (refresh_token 없음)

operation::member-refresh-401-no-cookie[snippets='http-request,http-response']


=== 4. 로그아웃

==== 4-1. 로그아웃 성공

operation::member-logout[snippets='http-request,http-response,response-headers']